### ISSUE TITLE
希望在软件中加入更多越南语和泰国语 

### ISSUE THREAD

**Issue by quangtrung3112** [emisjerry/autosub-ahk#4]
非常感谢 Jian Rui。 你非常热情，非常关心社区，所以我订阅了你的频道。 由于需要学习重要文件，强烈建议您在软件中添加越南语和泰语。 再次非常感谢您，并祝您和您的家人身体健康，在 COVID-19 大流行期间工作顺利。

**Comment by emisjerry** [comment]
Please view this video: https://youtu.be/fBIiuCxMHJE
or http://jdev.tw/blog/6691/autosub-ahk-ini-settings

**Comment by quangtrung3112** [comment]
I have done step 2. Can you tell me the software to do step one.
